package core

import (
	"os"
	"strings"
)

const PluginVersion = "0.0.6"

var FileHeaderComment = strings.Join([]string{
	"// Code generated by sqlc. DO NOT EDIT.",
	"// versions:",
	"//   sqlc " + os.Getenv("SQLC_VERSION"),
	"//   sqlc-gen-java " + PluginVersion,
}, "\n")
